### ISSUE TITLE
NodeClipse only allows debugging of 1 .js file at a time

### ISSUE THREAD

**Issue by rapiddata** [Nodeclipse/www.nodeclipse.org#64] opened 2015-03-20 18:23 UTC
NodeClipse only allows debugging of 1 .js file
If I set a breakpoint in a different .js file the breakpoint is never hit.
Error is source is not available.
NodeClipse is not able to load source of different files in the debug stack.
Maybe because I am running Current Version: v0.12.0 of Node.js because it used to work with an earlier version of Node.js.
I am also running Eclipse Luna SR2 on Windows 7.

**Comment by paulvi** [comment] 2015-09-25 08:35
closing as duplicate of https://github.com/Nodeclipse/nodeclipse-1/issues/189

besides it anyways should be in https://github.com/Nodeclipse/nodeclipse-1/issues/

try Nodeclipse 1.x with Node 4.x

**Closed as completed by paulvi** 2015-09-25 08:35 UTC
